### ISSUE TITLE
Docs: make it explicit that ODBC requires at least the Basic license

### ISSUE THREAD

**Issue by bpintea** [elastic/elasticsearch-sql-odbc#128]
as per https://discuss.elastic.co/t/setting-up-odbc-connection-to-es-v6-6/170941

**Comment by droberts195** [comment]
https://www.elastic.co/subscriptions says ODBC requires a platinum license

**Comment by bpintea** [comment]
> https://www.elastic.co/subscriptions says ODBC requires a platinum license

True. I've only added a note about ODBC requiring the SQL plugin loaded (https://github.com/elastic/elasticsearch/pull/40476/files) and kept away from licensing (should that change).

**Comment by bpintea** [comment]
Fixed in https://github.com/elastic/elasticsearch/pull/40476
