### ISSUE TITLE
Installation prerequisites check

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch-sql-odbc#146]
https://www.elastic.co/guide/en/elasticsearch/reference/current/sql-odbc-installation.html
The doc says: "If you fail to meet any of the prerequisites the installer will show an error message and abort the installation."

I installed ODBC driver 6.7.0 (esodbc-6.7.0-windows-x86) on a Windows Server 2012 R2 Datacenter machine (Windows Server 6.3 Build 9600) and it installs successfully without an error even though it does not meet the prerequisites.

**Comment by bpintea** [comment]
Thanks, @ppf2 .
I will change the wording on that one, since we don't necessarily want to restrict usage on other Windows releases. But except that first requirement, I believe the installer does bail out on missing prerequisites, since without those the driver wouldn't work.
