### ISSUE TITLE
Code signing is broken as of at least v7.3.0

### ISSUE THREAD

**Issue by ygel** [elastic/elasticsearch-sql-odbc#195]
### Environment
Agnostic

### Expected Behaviour
Have "Digital Signature" tab in explorer shell properties and cert embedded in MSI.

### Actual Behaviour
Both absent

### Notes:
I checked ODBC repo and unified build sources, everything looks legit on cursory examination. 

refs: https://github.com/elastic/infra/issues/9904

**Comment by bpintea** [comment]
Fixed by #197, #198.
