### ISSUE TITLE
Add a backwards compatibility working mode

### ISSUE THREAD

**Issue by bpintea** [elastic/elasticsearch-sql-odbc#206]
Some of the 2.x applications - or even 3.x ones, updated from a 2.x base - make use of the ODBC API in a way that is currently difficult to support with ES/SQL API:

* [x] They prepare a statement with `SQLPrepare`, then require attributes of the columns that would be later fetched (by `SQLExecute`), with `SQLNumResultCols` and `SQLColAttribute`. 
This is difficult to support since there's no concept of statement preparation in ES/SQL. However, the driver could detect the pattern and issue something like `SELECT * FROM (<original statement>) WHERE false`. :: #227 

* [ ] They require the available rows after executing a statement, with `SQLRowCount`. The count is not currently available in ES/SQL API, which would need to be expanded, or, alternatively, the driver could issue something like `SELECT COUNT(*) FROM (<original staement>)`.

* [x] Another case is the way tables are reported (`TABLE` vs `BASE TABLE`). The current server-side heuristic doesn't cover all clients expecting one format or the other and having a driver-side switch (=config option) both simplifies the server-code and makes the driver more useful with these apps. :: https://github.com/elastic/elasticsearch/pull/54836

This usage patterns are now discouraged or warned against by the current ODBC documentation, but not disallowed.

**Comment by bpintea** [comment]
3. Another case is the way tables are reported (`TABLE` vs `BASE TABLE`). The current server-side heuristic doesn't cover all clients expecting one format or the other and having a driver-side switch (=config option) both simplifies the server-code and makes the driver more useful with these apps.

**Comment by matriv** [comment]
Relevant issue to row count: https://github.com/elastic/elasticsearch/issues/52787

**Comment by bpintea** [comment]
The total row count point [can not be efficiently implemented](https://github.com/elastic/elasticsearch/issues/54422) on the server side. A "cheaper" subquery workaround (`SELECT count(1) FROM (<original query>)`) is currently also not reliably available, so the only alternative is to fetch all rows just to count them, which is also not feasible (even if with a narrowed projection) in all cases.
