### ISSUE TITLE
Add Version type support

### ISSUE THREAD

**Issue by bpintea** [elastic/elasticsearch-sql-odbc#311]
Add support for new Version type, introduced in SQL by https://github.com/elastic/elasticsearch/pull/85502.

**Comment by costin** [comment]
This is a blocking bug as the driver reports the same version as the server which sends back the newly introduced type which the driver does not understand and as such fails right away.
The workaround is to use an ODBC version before 8.4.0 (such as 8.3.3) however clearly this is a poor experience.
