### ISSUE TITLE
MSI packages for ODBC Client 8.5.3 is not visible

### ISSUE THREAD

**Issue by sakurai-youhei** [elastic/elasticsearch-sql-odbc#316]
### Issue

Neither of the following pages shows links for the MSI packages as of Dec. 19, 2022.

<details>
 <summary>https://www.elastic.co/downloads/odbc-client</summary>

![image](https://user-images.githubusercontent.com/721858/208355057-4d5e52e7-1c67-46c2-8f95-fe195bc20b5f.png)

</details>

<details>
 <summary>https://www.elastic.co/jp/downloads/past-releases/odbc-client-8-5-3</summary>

![image](https://user-images.githubusercontent.com/721858/208355103-6ee81bca-a0c1-4b6f-a926-fb59e96d1318.png)

</details>

Note: The following direct links seem to be alive, though.

- https://artifacts.elastic.co/downloads/elasticsearch/esodbc-8.5.3-windows-x86_64.msi
- https://artifacts.elastic.co/downloads/elasticsearch/esodbc-8.5.3-windows-x86.msi

### Expected Behaviour

Download links should be visible like this.
![image](https://user-images.githubusercontent.com/721858/208355280-f9a484bd-0092-41ac-a2cd-b229663aabc4.png)

**Comment by bpintea** [comment]
Thanks for raising this, @sakurai-youhei. It's been now addressed.
