### ISSUE TITLE
Installer: the 64-bit installer launches the 32-bit Administrator

### ISSUE THREAD

**Issue by bpintea** [elastic/elasticsearch-sql-odbc#75]
At the end of running the installer for the 64-bit driver, the installer will launch `ODBC Data Source Administrator (32-bit)`, instead of the `... (64-bit)` version.

**Comment by codebrain** [comment]
Looks like we need to use a different custom action routine as it does not appear possible to alter the default working directory of the `WixShellExec` custom action.

https://sourceforge.net/p/wix/bugs/1386/

**Comment by codebrain** [comment]
(Hopefully) fixed in: https://github.com/elastic/elasticsearch-sql-odbc/pull/79

**Comment by codebrain** [comment]
Implemented as a CustomAction as using the WixShellExecTarget only ever launches a 32 bit process, then attempting to access any 64 bit programs will succumb to windows path rewriting and resolve to 32 bit equivalent program.
